package com.example.plas.domain.counting.entity

import com.example.plas.domain.essay.entity.Essay
import com.example.plas.domain.research.entity.Research
import javax.persistence.*

class PsyPosCountingDto(psyPosCounting: PsyPosCounting) {
    var essayId: Long? = 0

    var psySentence: Int? = null
    var psyWord: Int? = null
    var morphem: Int? = null
    var wpers: Float? = null
    var mpers: Float? = null

    var a1: Int? = null
    var a11: Int? = null
    var a111: Int? = null
    var a112: Int? = null
    var a113: Int? = null
    var a114: Int? = null
    var a12: Int? = null
    var a121: Int? = null
    var a122: Int? = null
    var a123: Int? = null
    var a124: Int? = null
    var a125: Int? = null
    var b1: Int? = null
    var b11: Int? = null
    var b12: Int? = null
    var b13: Int? = null
    var b14: Int? = null
    var b141: Int? = null
    var b142: Int? = null
    var b143: Int? = null
    var b15: Int? = null
    var b16: Int? = null
    var b17: Int? = null
    var c1: Int? = null
    var c11: Int? = null
    var c12: Int? = null
    var c13: Int? = null
    var c14: Int? = null
    var c15: Int? = null
    var c16: Int? = null
    var d1: Int? = null
    var d11: Int? = null
    var d12: Int? = null
    var d13: Int? = null
    var d14: Int? = null
    var d15: Int? = null
    var d16: Int? = null
    var e1: Int? = null
    var e11: Int? = null
    var e111: Int? = null
    var e112: Int? = null
    var e113: Int? = null
    var e114: Int? = null
    var e115: Int? = null
    var e12: Int? = null
    var e121: Int? = null
    var e122: Int? = null
    var e123: Int? = null
    var e124: Int? = null
    var e125: Int? = null
    var e2: Int? = null
    var e21: Int? = null
    var e22: Int? = null
    var f1: Int? = null
    var f11: Int? = null
    var f12: Int? = null
    var f13: Int? = null
    var g1: Int? = null
    var g11: Int? = null
    var g12: Int? = null
    var g13: Int? = null
    var g14: Int? = null
    var h1: Int? = null
    var i1: Int? = null
    var i11: Int? = null
    var i12: Int? = null
    var i13: Int? = null
    var i14: Int? = null
    var j1: Int? = null
    var j11: Int? = null
    var j12: Int? = null
    var k1: Int? = null
    var l1: Int? = null
    var m1: Int? = null
    var n1: Int? = null
    var z: Int? = null

    init {
        this.essayId = psyPosCounting.essay.id
        this.psySentence = psyPosCounting.psySentence
        this.psyWord = psyPosCounting.psyWord
        this.morphem = psyPosCounting.morphem
        this.wpers = psyPosCounting.wpers
        this.mpers = psyPosCounting.mpers
        this.a1 = psyPosCounting.a1
        this.a11 = psyPosCounting.a11
        this.a111 = psyPosCounting.a111
        this.a112 = psyPosCounting.a112
        this.a113 = psyPosCounting.a113
        this.a114 = psyPosCounting.a114
        this.a12 = psyPosCounting.a12
        this.a121 = psyPosCounting.a121
        this.a122 = psyPosCounting.a122
        this.a123 = psyPosCounting.a123
        this.a124 = psyPosCounting.a124
        this.a125 = psyPosCounting.a125
        this.b1 = psyPosCounting.b1
        this.b11 = psyPosCounting.b11
        this.b12 = psyPosCounting.b12
        this.b13 = psyPosCounting.b13
        this.b14 = psyPosCounting.b14
        this.b141 = psyPosCounting.b141
        this.b142 = psyPosCounting.b142
        this.b143 = psyPosCounting.b143
        this.b15 = psyPosCounting.b15
        this.b16 = psyPosCounting.b16
        this.b17 = psyPosCounting.b17
        this.c1 = psyPosCounting.c1
        this.c11 = psyPosCounting.c11
        this.c12 = psyPosCounting.c12
        this.c13 = psyPosCounting.c13
        this.c14 = psyPosCounting.c14
        this.c15 = psyPosCounting.c15
        this.c16 = psyPosCounting.c16
        this.d1 = psyPosCounting.d1
        this.d11 = psyPosCounting.d11
        this.d12 = psyPosCounting.d12
        this.d13 = psyPosCounting.d13
        this.d14 = psyPosCounting.d14
        this.d15 = psyPosCounting.d15
        this.d16 = psyPosCounting.d16
        this.e1 = psyPosCounting.e1
        this.e11 = psyPosCounting.e11
        this.e111 = psyPosCounting.e111
        this.e112 = psyPosCounting.e112
        this.e113 = psyPosCounting.e113
        this.e114 = psyPosCounting.e114
        this.e115 = psyPosCounting.e115
        this.e12 = psyPosCounting.e12
        this.e121 = psyPosCounting.e121
        this.e122 = psyPosCounting.e122
        this.e123 = psyPosCounting.e123
        this.e124 = psyPosCounting.e124
        this.e125 = psyPosCounting.e125
        this.e2 = psyPosCounting.e2
        this.e21 = psyPosCounting.e21
        this.e22 = psyPosCounting.e22
        this.f1 = psyPosCounting.f1
        this.f11 = psyPosCounting.f11
        this.f12 = psyPosCounting.f12
        this.f13 = psyPosCounting.f13
        this.g1 = psyPosCounting.g1
        this.g11 = psyPosCounting.g11
        this.g12 = psyPosCounting.g12
        this.g13 = psyPosCounting.g13
        this.g14 = psyPosCounting.g14
        this.h1 = psyPosCounting.h1
        this.i1 = psyPosCounting.i1
        this.i11 = psyPosCounting.i11
        this.i12 = psyPosCounting.i12
        this.i13 = psyPosCounting.i13
        this.i14 = psyPosCounting.i14
        this.j1 = psyPosCounting.j1
        this.j11 = psyPosCounting.j11
        this.j12 = psyPosCounting.j12
        this.k1 = psyPosCounting.k1
        this.l1 = psyPosCounting.l1
        this.m1 = psyPosCounting.m1
        this.n1 = psyPosCounting.n1
        this.z = psyPosCounting.z
    }
}